[package]
name = "izu-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[features]
fault-injection = ["izu-store/fault-injection"]

[dependencies]
izu-model.workspace = true
izu-store.workspace = true
izu-merge.workspace = true
izu-platform = { path = "../izu-platform", version = "0.1.0" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
getrandom.workspace = true
ignore.workspace = true

[dev-dependencies]
tempfile.workspace = true
